/* Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.
*/

package main

import "fmt"

var (
	f1 uint64 = 1
	f2 uint64 = 2
	f3 uint64 = 0
	sum uint64 = 2
)

func main() {
	for f3 < 4000000 {
		f3 = f1 + f2
		f1 = f2
		f2 = f3
		if f3%2 == 0 {
			sum = sum + f3
		}
	}
	fmt.Println(sum)
}
